auctions/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.conf import settings

from . import views
app_name = 'auctions'

urlpatterns = [
    path('create/', views.create, name='create'),
    # path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),

    path('index', views.index, name="index"),
    path('myauctions/', views.my_auctions, name="my_auctions"),
    path('mybids/', views.my_bids, name="my_bids"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx/urls.py
from django.contrib import admin
from django.urls import path,include
import captcha.urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('captcha/', include(captcha.urls))
    
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

auctions/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from datetime import timedelta, datetime, timezone
from math import ceil
from django.core.mail import send_mail
# Auction duration in minutes



class Auction(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=300)
    desc = models.CharField(max_length=2000, blank=True)
    contact=models.TextField(default=7889307466)
    image = models.ImageField(upload_to='item_images/', blank=True)
    min_value = models.IntegerField()
    date_added = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    duration = models.PositiveIntegerField(default=5)  # Default duration in minutes
    winner = models.ForeignKey(User, on_delete=models.SET("(deleted)"),
                               blank=True,
                               null=True,
                               related_name="auction_winner",
                               related_query_name="auction_winner")
    final_value = models.IntegerField(blank=True, null=True)

    def resolve(self):
        if self.is_active:
            if self.has_expired():
                highest_bid = Bid.objects.filter(auction=self).order_by('-amount', '-date').first()
                if highest_bid:
                    self.winner = highest_bid.bidder
                    self.final_value = highest_bid.amount
                    self.is_active = False
                    self.save()
                    if self.winner is not None:
                       self.handle_resolution()
                else:
                    self.is_active=False
                    self.winner=None
                    self.save()
        highest_bid = Bid.objects.filter(auction=self).order_by('-amount', '-date').first()
        if highest_bid:
            return highest_bid.amount
        else:
             self.is_active=False
             return None   
  
        

    # Helper function that determines if the auction has expired
    def has_expired(self):
        now = datetime.now(timezone.utc)
        expiration = self.date_added + timedelta(minutes=self.duration)
        if now > expiration:
            return True
        else:
            return False

    # Returns the ceiling of remaining_time in minutes
    @property
    def remaining_minutes(self):
        if self.is_active:
            now = datetime.now(timezone.utc)
            expiration = self.date_added + timedelta(minutes=self.duration)
            minutes_remaining = ceil((expiration - now).total_seconds() / 60)
            if minutes_remaining<0:
                return 0
            else:
                return(minutes_remaining)
        else:
            return(0)

    def handle_resolution(self):
        # Send notification to the winner
        send_winner_notification(self.winner, self)

        # Send notification to the owner (author) of the auction
        send_owner_notification(self.author, self)

    # ... (other methods)


class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE)
    amount = models.IntegerField()
    # is_cancelled = models.BooleanField(default=False)
    date = models.DateTimeField('when the bid was made')

def send_winner_notification(winner, auction):
       subject = 'Congratulations! You won the auction'
       message = f'Congratulations! You won the auction for {auction.title}.'
       from_email = 'olx6094@gmail.com'  # Replace with your email
       recipient_list = [auction.winner.email]
   
       send_mail(subject, message, from_email, recipient_list, fail_silently=False)

def send_owner_notification(owner, auction):
        subject = f'Your product {auction.title} has been sold'
        message = f'Your product {auction.title} has been sold in the auction. The winner is {auction.winner.username}.'
        from_email = 'olx6094@gmail.com'  # Replace with your email
        recipient_list = [owner.email]
    
        send_mail(subject, message, from_email, recipient_list, fail_silently=False)


auctions/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()


auctions/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.contrib.auth.decorators import login_required
from datetime import datetime, timezone
from django.urls import reverse
from .notification import send_winner_notification 
from django.views.decorators.http import require_POST
from .models import Auction, Bid
from .forms import ImageUploadForm

# Main page
def index(request):
    # First get all auctions and resolve them
    auction_list = Auction.objects.all()
    for a in auction_list:
        a.resolve()
    # Get all active auctions, oldest first
    latest_auction_list = auction_list.filter(is_active=True).order_by('date_added')
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "Active auctions",
        'auction_list': latest_auction_list,
    }
    return HttpResponse(template.render(context, request))

def auctions(request):
    # Get all auctions, newest first
    auction_list = Auction.objects.order_by('-date_added')
    for a in auction_list:
        a.resolve()
    template = loader.get_template('auctions/index.html')
    context = {
        'title': "All auctions",
        'auction_list': auction_list,
    }
    return HttpResponse(template.render(context, request))

# Details on some auction
def detail(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    already_bid = False
    if request.user.is_authenticated:
        if auction.author == request.user:
            own_auction = True
            return render(request, 'auctions/detail.html', {'auction': auction, 'own_auction': own_auction})

        user_bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()
        if user_bid:
            already_bid = True
            bid_amount = user_bid.amount
            return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid, 'bid_amount': bid_amount})

    return render(request, 'auctions/detail.html', {'auction': auction, 'already_bid': already_bid})
    # try:
    #     auction = Auction.objects.get(pk=auction_id)
    # except Auction.DoesNotExist:
    #     raise Http404("Auction does not exist")
    # return render(request, 'auctions/detail.html', {'auction': auction})

# def results(request, auction_id):
#     response = "You're looking at the results of auction %s."
#     return HttpResponse(response % auction_id)

# Bid on some auction
@login_required
def bid(request, auction_id):
    auction = get_object_or_404(Auction, pk=auction_id)
    auction.resolve()
    bid = Bid.objects.filter(bidder=request.user).filter(auction=auction).first()
    if not auction.is_active:
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "The auction has expired.",
        })

    try:
        bid_amount = request.POST['amount']
        # Prevent user from entering an empty or invalid bid
        highest_bid = Bid.objects.filter(auction=auction).order_by('-amount').first()
        if highest_bid:
         if not bid_amount or int(bid_amount) < highest_bid.amount:
            raise(KeyError)
        else:
              if not bid_amount or int(bid_amount) < auction.min_value:
               raise(KeyError)
        if not bid:
            # Create new Bid object if it does not exist
            bid = Bid()
            bid.auction = auction
            bid.bidder = request.user
        bid.amount = bid_amount
        bid.date = datetime.now(timezone.utc)
        bid.save()
    except (KeyError):
        # Redisplay the auction details.
        return render(request, 'auctions/detail.html', {
            'auction': auction,
            'error_message': "Invalid bid amount.",
        })
    else:
        

        return redirect('auctions:index')


# Create auction
@login_required
def create(request):
    submit_button = request.POST.get('submit_button')
    if submit_button:
        try:
            title = request.POST['title']
            auction_duration = request.POST['duration']
            min_value = request.POST['min_value']
            contact= request.POST['contact']

            if not title or not min_value or not contact:
                raise(KeyError)
        except (KeyError):
            # Redisplay the create auction page with an error message.
            return render(request, 'auctions/create.html', {
                'error_message': "Please fill the required fields.",
            })
        else:
            # Create new Bid object
            auction = Auction()
            auction.author = request.user
            auction.title = title
            auction.duration=auction_duration
            auction.min_value = min_value
            auction.contact=contact
            auction.desc = request.POST['description']
            img = request.FILES.get('img')  # Use get to avoid MultiValueDictKeyError
            auction.image=img
            # auction.date_added = datetime.utcnow()
            auction.date_added = datetime.now(timezone.utc)
            auction.save()
            # return HttpResponseRedirect(reverse('auctions:detail', args=(auction.id,)))
            return redirect('auctions:my_auctions')
    else:
        return render(request, 'auctions/create.html')


@login_required
def my_auctions(request):
    # Get all auctions by user, sorted by date
    my_auctions_list = Auction.objects.all().filter(author=request.user).order_by('-date_added')
    for a in my_auctions_list:
        a.resolve()
    template = loader.get_template('auctions/my_auctions.html')
    context = {
        'my_auctions_list': my_auctions_list,
    }
    return HttpResponse(template.render(context, request))

@login_required
def my_bids(request):
    # Get all bids by user, sorted by date
    my_bids_list = Bid.objects.all().filter(bidder=request.user).order_by('-date')
    for b in my_bids_list:
        b.auction.resolve()

    template = loader.get_template('auctions/my_bids.html')
    context = {
        'my_bids_list': my_bids_list,
    }
    return HttpResponse(template.render(context, request))


auctions/templates/auctions/create.html
{% extends "base2.html" %}
{% block content %}
<style>
    /* Reset some default styles */
body, h1, h2, h3, p, ul, li {
    margin: 0;
    padding: 0;
}

/* Apply a basic body style */
body {
    font-family: 'Arial', sans-serif;
    background-color: #f4f4f4;
}

/* Style the wrapper div */
.wrapper {
    max-width: 600px;
    margin: 30px auto;
    padding: 20px;
    background-color: #fff;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

/* Style the form elements */
form {
    display: flex;
    flex-direction: column;
}

span {
    font-weight: bolder;
    margin-bottom: 5px;
}

.textbox, .description_box, .duration, .submit_button {
    margin-bottom: -15px;
    padding: 6px;
    width: 100%;
    background-color: darkgray;
    font-weight: bolder;
}

.description_box {
    height: 85px;
}

/* Style the submit button */
.submit_button {
    background-color: #4CAF50;
    color: #fff;
    cursor: pointer;
}

/* Add hover effect to submit button */
.submit_button:hover {
    background-color: #45a049;
}
.duration{
    border: none;
}

</style>
<h1>Create Auction</h1>
<div class="wrapper">
    <form action="{% url 'auctions:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <span>Enter title:</span>
        <br>
        <input class="textbox" type="text" name="title" required>
        <br>
        <br>
        <span>Enter description:</span>
        <br>
        <input class="description_box" type="text" name="description" required>
        <br>
        <span>Your Contact:</span>
        <br>
        <input class="textbox" type="text" name="contact" required>
        <br>
        <span>Enter Duration:</span>
        <br>
        <input class="duration" type="number" name="duration" required>
        <br>
        <br>
        <span>Upload picture:</span>
        <br>
        <input class="textbox" type="file" name="img" required>
        <br>
        <br>
        <span>Enter minimum value:</span>
        <br>
        <input class="textbox" type="text" name="min_value" required>
        <br>
        <br>
        <input type="submit" class="submit_button" name="submit_button" value="Create">
    </form>
</div>
{% endblock %}

auctions/templates/auctions/detail.html
{% extends "base2.html" %}
{% block content %}

{% block title %}<title>{{ auction.title }}Bidding</title>{% endblock %}
<style>
    span{
        font-weight: bolder;
    }
    .textbox{
        background-color: darkgrey;
    }
    .desc_box{
        background-color: darkgray;
        font-weight: bold;
    }
</style>
<h1> {{ auction.title }} </h1>
<div class="wrapper">
    <span class="auction-card">
        <span><img class="auction_image_index" src="{{ auction.image.url }}"></span>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}m</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}m</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">{{ auction.min_value }}$</div>
        </div>
    </span>
</div>
<div class="wrapper">
    {% if not own_auction %}
        {% if auction.is_active %}
        <!-- <div class="bid_box"> -->
        <form action="{% url 'auctions:bid' auction.id %}" method="post">
        <!-- <form action="/auctions/{{ auction.id }}/bid/" method="post"> -->
        {% csrf_token %}
        <div class="input_label">
        {% if error_message %}<p class="error" style="margin-left: 52px;" ><strong>{{ error_message }}</strong></p>{% endif %}
        
        <h3> Current bid: {% if  auction.resolve %}{{ auction.resolve }}{% else %}No bids yet{% endif %} </h3>

        
        <span>Enter amount ($):</span>
        <span class="required_field" >*</span>
        </div>
        <input class="textbox" type="text" class="input_box" name="amount">
        <br>
        <a><input class="submit_button" type="submit" class="submit_button" value="Bid"></a>
        </form>
        <br>
        <!-- </div> -->
        {% endif %}
    {% endif %}
</div>

{% if auction.desc %}
<div class="wrapper">
    <div class="desc_box">
    <div class="desc_box_title">Description</div>
    <hr>
    {{ auction.desc }}
    </div>
</div>
{% endif %}

{% endblock %}

auctions/templates/auctions/index.html
{% extends "base2.html" %}
{% block content %}

<h1>{{ title }}</h1>
{% if auction_list %}
    <div class="wrapper">
    {% for auction in auction_list %}
       
        <a class="auction-card" href="{% url 'auctions:detail' auction.id %}">
            <div><img class="auction_image_index" src="{{ auction.image.url }}"></div>
            <div class="auction-card-title">{{ auction.title }}</div>
            {% if auction.is_active %}
                {% if auction.remaining_minutes < 2 %}
                    <div class="auction-card-urgent">Less than {{ auction.remaining_minutes }}m</div>
                {% else %}
                    <div class="auction-card-active">Less than {{ auction.remaining_minutes }}m</div>
                {% endif %}
            {% else %}
            <div class="auction-card-inactive">Expired</div>
            {% endif %}
            <div class="auction-card-value">{{ auction.min_value }}$</div>
        </a>
        <!-- <li class="auction-card"><a href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a></li> -->
    {% endfor %}
    </div>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/my_auctions.html
{% extends "base2.html" %}
{% block title %}<title>My-Auction</title>{% endblock %}
{% block content %}
<style>
    h2{
        font-weight: bolder;
        font-size:xx-large;
    }
</style>
<h2> My Auctions </h2>
{% if my_auctions_list %}
    <ul class="my-auction-list">
    {% for auction in my_auctions_list %}
        <li class="my-auction-li"><a class="my-auction-link" href="{% url 'auctions:detail' auction.id %}">{{ auction.title }}</a>
            <div class="my-auction-date">Added: {{ auction.date_added }}</div>

            <hr>
            {% if auction.is_active %}
                <span class="my-auction-status-active">
                    Pending
                </span>
                <span class="my-auction-value">
                    {{ auction.min_value }}$
                </span>
            {% else %}
                {% if auction.final_value %}
                <div class="result" style="display: flex; justify-content: space-between; width: 100%;">
                <span class="my-auction-status-resolved">
                    Final value: {{ auction.final_value }}$
                </span>
                <span class="my-auction-status-resolved">
                    Winner: {{ auction.winner.username }}
                </span>
                </div>
                {% else %}
                <span class="my-auction-status-no_winner">
                    No winner
                </span>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% else %}
    <h4>No auctions are available.</h4>
{% endif %}

{% endblock %}

auctions/templates/auctions/my_bids.html
{% extends "base2.html" %}
{% block title %}<title>My Bids - Auction Rush</title>{% endblock %}
{% block content %}
<style>
    h2{
        font-weight: bolder;
        font-size:xx-large;
    }
    .winning{
        display: flex;
    }
    .con{
        margin-left: 170px;
    }
</style>
<h2> My Bids </h2>
{% if my_bids_list %}
<ul class="my-bid-list">
    {% for bid in my_bids_list %}
        <li class="my-bid-li"><a class="my-bid-link" href="{% url 'auctions:detail' bid.auction.id %}">{{ bid.auction.title }}</a>
            {% if bid.auction.winner and bid.auction.winner == user %}
           <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeRwRaqaK8osbBbd0Je9e04kWy_ZCCFsdTFQ&usqp=CAU" alt="">
           {% elif bid.auction.is_active %}
           <img src="https://t3.ftcdn.net/jpg/04/25/61/02/360_F_425610274_iTsjecWWkw4C37CDp5EBclLZg7x4fsKE.jpg" alt="" style="width: 368px;height: 137px;">
           {% else %}
           <img src="https://previews.123rf.com/images/gorkemdemir/gorkemdemir1409/gorkemdemir140901262/31998728-better-luck-next-time-red-rubber-stamp-text-vector-over-a-white-background.jpg" alt="" style="width: 368px;height: 137px;">
           {% endif %}

            <hr>
            <div class="my-bid-label">
                My last bid: {{ bid.amount }}$
                <div class="my-bid-date">({{ bid.date }})</div>
            </div>
            {% if bid.auction.is_active %}
                <div class="my-bid-status-active">Pending</div>
            {% else %}
                {% if bid.auction.winner and bid.auction.winner == user %}
                <div class="winning">
                <div class="my-bid-status-won">Contact Seller {{ bid.auction.contact}}</div>
                 <div class="my-bid-status-won con">Won for {{ bid.amount }}(INR)</div>
                </div>
                {% else %}
                    <div class="my-bid-status-lost">Lost</div>
                {% endif %}
            {% endif %}
        </li>
    {% endfor %}
</ul>
{% else %}
    <h4>No bids are available.</h4>
{% endif %}

{% endblock %}